---
# The variables are separated out to make it easier to update.

php:
  version: "8.4"
  extensions: >-
    bcmath,ctype,curl,dom,exif,fileinfo,filter,gd,iconv,imagick,intl,
    mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pdo,pdo_mysql,
    phar,posix,readline,redis,session,simplexml,soap,sockets,sodium,
    tokenizer,xml,xmlreader,xmlwriter,zip,zlib

caddy_modules: >-
  --with github.com/dunglas/caddy-cbrotli
  --with github.com/dunglas/mercure/caddy
  --with github.com/dunglas/vulcain/caddy
  --with github.com/stephenmiracle/frankenwp/sidekick/middleware/cache

published:
  # Published image name and version
  name: "frankenphp-wordpress"
  version: "v0.1.0"
