---
# The variables are separated out to make it easier to update.

php:
  version: "8.4"

wordpress:
  version: latest

frankenphp:
  # Docker URL and version
  url: "docker.io/dunglas/frankenphp"
  builder_version: "builder-php8.4"
  runtime_version: "1.9"

caddy:
  url: docker.io/caddy
  version: "2.10"

published:
  # Published image name and version
  name: "frankenphp-wordpress"
  version: "v0.1.0"
