---
# The variables are separated out to make it easier to update.

opensuse:
  # Docker URL and version
  name: leap
  url: "docker.io/opensuse/leap"
  version: "15.6"

published:
  # Published image name and version
  name: "opensuse-base"
  # The openSUSE name and version is appended: v0.1.1-leap-15.6
  version: "v0.3.5"

packages:
  list:
    # The user inside the container is "dev"
    - sudo
    # Basic utils
    - vim
    - vim-data
    - git
    - tar
    - gzip
    - bzip2
    - zstd
    - which
    # Required for Forgejo actions
    - nodejs-common
    - openssh-clients
    # Needed for remote development with JetBrains
    - java-21-openjdk-devel
    # Container tools
    - buildah
    - docker
    - docker-compose
    - docker-buildx
    - fuse-overlayfs
    # Development
    - clang
    - libopenssl-devel
    - gcc

binaries:
  host: dufs.niceguyit.biz
  list:
    - name: age
      version: "v1.1.1"
    - name: btm
      version: "0.10.2"
    - name: bun
      version: "v1.3"
    - name: chezmoi
      version: "v2.54.0"
    - name: doggo
      version: "v0.5.7"
    - name: fd
      version: "8.7.1"
    - name: gh
      version: "2.41.0"
    - name: just
      version: "1.42.4"
    - name: kingfisher
      version: "1.59.0"
    # FIXME: Upgrade Nebula to the latest.
    - name: nebula
      version: "1.8.0"
    - name: noseyparker
      version: "v0.24.0"
    - name: nu
      version: "0.101.0"
    - name: nu
      version: "0.101.0"
      file: nu_plugin_formats
    - name: nu
      version: "0.101.0"
      file: nu_plugin_gstat
    - name: nu
      version: "0.101.0"
      file: nu_plugin_inc
    - name: nu
      version: "0.101.0"
      file: nu_plugin_polars
    - name: nu
      version: "0.101.0"
      file: nu_plugin_query
    - name: ouch
      version: "0.5.1"
    - name: pinger
      version: "v1.3.1"
    - name: rage
      version: "v0.11.1"
    - name: rg
      version: "14.0.3"
    - name: rclone
      version: "v1.70.3"
    - name: starship
      version: "v1.22.1"
    - name: trufflehog
      version: "3.90.11"

dotfiles:
  repo: https://github.com/NiceGuyIT/dotfiles.git
