---
# Build WordPress and push to GHCR.
name: Build WordPress container

on:
  push:
    paths:
      - "wordpress/**"
      - ".github/workflows/build-wordpress.yml"

jobs:
  build:
    name: Build Wordpress image
    uses: ./.github/workflows/build-and-push-image.yml
    permissions:
      contents: read
      packages: write
    with:
      image-name: wordpress
      image-type: base
